Adding stable column

diff --git a/.github/workflows/cirq-stable-stable.yml b/.github/workflows/cirq-stable-stable.yml
--- a/.github/workflows/cirq-stable-stable.yml
+++ b/.github/workflows/cirq-stable-stable.yml
@@ -1,16 +1,18 @@
-name: qiskit-stable
+# Workflow template for testing plugin stable/PennyLane stable
+
+name: cirq-stable-stable
 on:
   push:
   pull_request:
   schedule:
-    - cron: '0 0 * * *'
+    - cron: '0 0 * * 0'
   workflow_dispatch:
 
 
 env:
-  PLUGIN_REPO: PennyLaneAI/pennylane-qiskit
+  PLUGIN_REPO: PennyLaneAI/pennylane-cirq
   PLUGIN_BRANCH: master
-  PLUGIN_PACKAGE: pennylane_qiskit
+  PLUGIN_PACKAGE: pennylane_cirq
   PENNYLANE_BRANCH: master
 
 
@@ -35,15 +37,14 @@ jobs:
       - name: Install requirements
         run: |
           pip install --upgrade pip
-          pip install --upgrade qiskit
-          pip install --upgrade pyscf==1.7.2
+          pip install --upgrade cirq
           pip install pytest pytest-mock pytest-cov flaky
           pip freeze
 
       - name: Install PennyLane and Plugin
         run: |
-          pip install git+https://github.com/PennyLaneAI/pennylane.git@${{ env.PENNYLANE_BRANCH }} \
-          ${{ env.PLUGIN_PACKAGE }}
+          pip install pennylane ${{ env.PLUGIN_PACKAGE }}
+          pip freeze
 
       - name: Get plugin version
         id: plugin-version
@@ -59,10 +60,14 @@ jobs:
 
       - name: Run PennyLane device integration tests
         run: |
-          pl-device-test --device=qiskit.basicaer --tb=short --skip-ops --analytic=False --shots=20000 --device-kwargs backend=qasm_simulator
-          pl-device-test --device=qiskit.aer --tb=short --skip-ops --analytic=False --shots=20000 --device-kwargs backend=qasm_simulator
-          pl-device-test --device=qiskit.basicaer --tb=short --skip-ops --analytic=True --device-kwargs backend=statevector_simulator
-          pl-device-test --device=qiskit.aer --tb=short --skip-ops --analytic=True --device-kwargs backend=unitary_simulator
+          if ! [ -x "$(command -v pl-device-test)" ]; then
+            echo 'Error: Version of PennyLane does not provide device integration tests.' >&2
+          else
+            pl-device-test --device=cirq.simulator --tb=short --skip-ops --analytic=True
+            pl-device-test --device=cirq.simulator --tb=short --skip-ops --analytic=False --shots=20000
+            pl-device-test --device=cirq.mixedsimulator --tb=short --skip-ops --analytic=True
+            pl-device-test --device=cirq.mixedsimulator --tb=short --skip-ops --analytic=False --shots=20000
+          fi
 
       - name: Run plugin tests
         run: python -m pytest plugin_repo/tests --tb=short
diff --git a/workflow-template-stable.yml b/workflow-template-stable.yml
--- a/workflow-template-stable.yml
+++ b/workflow-template-stable.yml
@@ -1,9 +1,11 @@
-name: {{ plugin }}-{% if latest %}latest{% else %}stable{% endif %}
+# Workflow template for testing plugin stable/PennyLane stable
+
+name: {{ plugin }}-stable-stable
 on:
   push:
   pull_request:
   schedule:
-    - cron: '0 0 * * *'
+    - cron: '0 0 * * 0'
   workflow_dispatch:
 
 
@@ -41,29 +43,12 @@ jobs:
           pip install pytest pytest-mock pytest-cov flaky
           pip freeze
 
-     {%- if latest %}
-
       - name: Install PennyLane and Plugin
         run: |
           {% raw -%}
-          pip install git+https://github.com/PennyLaneAI/pennylane.git@${{ env.PENNYLANE_BRANCH }} \
-            git+https://github.com/${{ env.PLUGIN_REPO }}.git@${{ env.PLUGIN_BRANCH }}
+          pip install pennylane ${{ env.PLUGIN_PACKAGE }}
           {%- endraw %}
-
-      - uses: actions/checkout@v2
-        with:
-          repository: {% raw %}${{ env.PLUGIN_REPO }}{% endraw %}
-          path: plugin_repo
-          ref: {% raw %}${{ env.PLUGIN_BRANCH }}{% endraw %}
-
-      {% else %}
-
-      - name: Install PennyLane and Plugin
-        run: |
-          {% raw -%}
-          pip install git+https://github.com/PennyLaneAI/pennylane.git@${{ env.PENNYLANE_BRANCH }} \
-          ${{ env.PLUGIN_PACKAGE }}
-          {%- endraw %}
+          pip freeze
 
       - name: Get plugin version
         id: plugin-version
@@ -79,13 +64,17 @@ jobs:
           path: plugin_repo
           ref: {% raw %}v${{ steps.plugin-version.outputs.version }}{% endraw %}
 
-      {% endif -%}
-
+      {% if device_tests -%}
       - name: Run PennyLane device integration tests
         run: |
-          {%- for test in device_tests %}
-          pl-device-test {{ test }}
-          {%- endfor %}
+          if ! [ -x "$(command -v pl-device-test)" ]; then
+            echo 'Error: Version of PennyLane does not provide device integration tests.' >&2
+          else
+            {%- for test in device_tests %}
+            pl-device-test {{ test }}
+            {%- endfor %}
+          fi
+      {%- endif %}
 
       - name: Run plugin tests
         run: python -m pytest plugin_repo/tests --tb=short
